import './globals.css';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
const inter = Inter({ subsets: ['latin'] });

import Navbar from './components/Navbar/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: '#10b981',
          colorBackground: '#292524',
          colorTextOnPrimaryBackground: '#e7e5e4',
          colorTextSecondary: '#a8a29e',
        },
      }}
    >
      <html lang="en" className="bg-stone-900 text-stone-200">
        <body className={inter.className}>
          <Navbar />
          <main className="container">
            <div className="flex items-start justify-center min-h-screen">
              <div className="mt-20">{children}</div>
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
